#!/bin/bash

# ALL 50 US States with multiple cities each
declare -a STATES=(
    # Alabama
    "AL: Alabama:Birmingham"
    "AL:Alabama: Montgomery"
    "AL:Alabama: Huntsville"
    "AL: Alabama:Mobile"
    # Alaska
    "AK:Alaska:Anchorage"
    "AK:Alaska:Fairbanks"
    "AK:Alaska:Juneau"
    # Arizona
    "AZ:Arizona:Phoenix"
    "AZ:Arizona:Tucson"
    "AZ:Arizona:Mesa"
    "AZ:Arizona:Scottsdale"
    "AZ:Arizona:Tempe"
    # Arkansas
    "AR:Arkansas:Little Rock"
    "AR:Arkansas:Fort Smith"
    "AR:Arkansas:Fayetteville"
    # California
    "CA:California: Los Angeles"
    "CA: California:San Francisco"
    "CA:California:San Diego"
    "CA:California:San Jose"
    "CA:California: Sacramento"
    "CA:California:Oakland"
    "CA:California: Fresno"
    "CA:California:Long Beach"
    "CA:California:Bakersfield"
    "CA:California:Anaheim"
    "CA:California: Santa Monica"
    "CA:California: Palo Alto"
    "CA: California:Berkeley"
    "CA:California: Irvine"
    # Colorado
    "CO:Colorado: Denver"
    "CO:Colorado:Colorado Springs"
    "CO:Colorado:Aurora"
    "CO: Colorado:Boulder"
    "CO:Colorado:Fort Collins"
    # Connecticut
    "CT:Connecticut: Hartford"
    "CT:Connecticut:New Haven"
    "CT:Connecticut:Stamford"
    "CT:Connecticut:Bridgeport"
    # Delaware
    "DE:Delaware:Wilmington"
    "DE:Delaware:Dover"
    "DE:Delaware: Newark"
    # Florida
    "FL:Florida: Miami"
    "FL:Florida:Orlando"
    "FL: Florida:Tampa"
    "FL:Florida: Jacksonville"
    "FL:Florida: Fort Lauderdale"
    "FL:Florida:St. Petersburg"
    "FL: Florida:Tallahassee"
    "FL:Florida:Gainesville"
    # Georgia
    "GA:Georgia: Atlanta"
    "GA:Georgia: Savannah"
    "GA: Georgia:Augusta"
    "GA:Georgia: Athens"
    "GA:Georgia: Macon"
    # Hawaii
    "HI:Hawaii:Honolulu"
    "HI:Hawaii:Hilo"
    "HI: Hawaii:Kailua"
    "HI:Hawaii:Pearl City"
    # Idaho
    "ID:Idaho:Boise"
    "ID:Idaho: Idaho Falls"
    "ID:Idaho:Pocatello"
    "ID: Idaho:Nampa"
    # Illinois
    "IL:Illinois: Chicago"
    "IL:Illinois:Springfield"
    "IL: Illinois:Naperville"
    "IL:Illinois:Rockford"
    "IL:Illinois:Peoria"
    "IL:Illinois:Evanston"
    # Indiana
    "IN:Indiana: Indianapolis"
    "IN:Indiana:Fort Wayne"
    "IN:Indiana:Evansville"
    "IN: Indiana:South Bend"
    "IN: Indiana:Bloomington"
    # Iowa
    "IA:Iowa:Des Moines"
    "IA:Iowa:Cedar Rapids"
    "IA: Iowa:Davenport"
    "IA:Iowa:Iowa City"
    # Kansas
    "KS:Kansas:Wichita"
    "KS:Kansas:Kansas City"
    "KS: Kansas:Topeka"
    "KS: Kansas:Overland Park"
    # Kentucky
    "KY:Kentucky:Louisville"
    "KY:Kentucky:Lexington"
    "KY:Kentucky:Bowling Green"
    "KY: Kentucky:Frankfort"
    # Louisiana
    "LA:Louisiana: New Orleans"
    "LA:Louisiana:Baton Rouge"
    "LA:Louisiana: Shreveport"
    "LA:Louisiana:Lafayette"
    # Maine
    "ME:Maine: Portland"
    "ME:Maine: Augusta"
    "ME:Maine: Bangor"
    # Maryland
    "MD:Maryland: Baltimore"
    "MD:Maryland: Annapolis"
    "MD:Maryland:Rockville"
    "MD:Maryland:Frederick"
    "MD:Maryland: Bethesda"
    # Massachusetts
    "MA:Massachusetts: Boston"
    "MA:Massachusetts:Cambridge"
    "MA:Massachusetts: Worcester"
    "MA:Massachusetts: Springfield"
    "MA:Massachusetts: Salem"
    # Michigan
    "MI:Michigan: Detroit"
    "MI:Michigan:Grand Rapids"
    "MI:Michigan:Ann Arbor"
    "MI:Michigan:Lansing"
    "MI:Michigan:Flint"
    # Minnesota
    "MN:Minnesota:Minneapolis"
    "MN:Minnesota:St. Paul"
    "MN:Minnesota:Rochester"
    "MN:Minnesota:Duluth"
    # Mississippi
    "MS:Mississippi: Jackson"
    "MS:Mississippi:Gulfport"
    "MS:Mississippi:Biloxi"
    "MS:Mississippi:Hattiesburg"
    # Missouri
    "MO:Missouri:Kansas City"
    "MO: Missouri:St. Louis"
    "MO:Missouri:Springfield"
    "MO:Missouri:Columbia"
    # Montana
    "MT:Montana: Billings"
    "MT: Montana:Missoula"
    "MT:Montana:Great Falls"
    "MT:Montana:Helena"
    # Nebraska
    "NE: Nebraska: Omaha"
    "NE:Nebraska:Lincoln"
    "NE:Nebraska:Bellevue"
    # Nevada
    "NV:Nevada:Las Vegas"
    "NV:Nevada:Reno"
    "NV:Nevada: Henderson"
    "NV: Nevada:Carson City"
    # New Hampshire
    "NH:New Hampshire:Manchester"
    "NH:New Hampshire:Concord"
    "NH:New Hampshire:Nashua"
    # New Jersey
    "NJ:New Jersey:Newark"
    "NJ:New Jersey:Jersey City"
    "NJ:New Jersey:Trenton"
    "NJ: New Jersey:Atlantic City"
    "NJ: New Jersey:Princeton"
    # New Mexico
    "NM:New Mexico: Albuquerque"
    "NM:New Mexico:Santa Fe"
    "NM:New Mexico:Las Cruces"
    "NM:New Mexico:Roswell"
    # New York
    "NY:New York:New York City"
    "NY: New York:Buffalo"
    "NY:New York:Albany"
    "NY:New York:Rochester"
    "NY:New York:Syracuse"
    "NY:New York:Yonkers"
    # North Carolina
    "NC:North Carolina:Charlotte"
    "NC:North Carolina:Raleigh"
    "NC:North Carolina:Durham"
    "NC:North Carolina:Greensboro"
    "NC:North Carolina:Asheville"
    # North Dakota
    "ND:North Dakota: Fargo"
    "ND:North Dakota:Bismarck"
    "ND: North Dakota:Grand Forks"
    # Ohio
    "OH:Ohio:Columbus"
    "OH:Ohio: Cleveland"
    "OH:Ohio:Cincinnati"
    "OH: Ohio:Toledo"
    "OH:Ohio: Akron"
    "OH:Ohio: Dayton"
    # Oklahoma
    "OK:Oklahoma: Oklahoma City"
    "OK: Oklahoma:Tulsa"
    "OK:Oklahoma:Norman"
    # Oregon
    "OR:Oregon: Portland"
    "OR:Oregon:Salem"
    "OR: Oregon:Eugene"
    "OR:Oregon: Bend"
    # Pennsylvania
    "PA:Pennsylvania: Philadelphia"
    "PA:Pennsylvania:Pittsburgh"
    "PA:Pennsylvania: Harrisburg"
    "PA:Pennsylvania:Allentown"
    "PA: Pennsylvania:Erie"
    # Rhode Island
    "RI: Rhode Island:Providence"
    "RI:Rhode Island:Newport"
    "RI:Rhode Island:Warwick"
    # South Carolina
    "SC:South Carolina:Charleston"
    "SC:South Carolina:Columbia"
    "SC:South Carolina: Greenville"
    "SC: South Carolina:Myrtle Beach"
    # South Dakota
    "SD:South Dakota:Sioux Falls"
    "SD:South Dakota: Rapid City"
    "SD: South Dakota:Pierre"
    # Tennessee
    "TN:Tennessee:Nashville"
    "TN:Tennessee:Memphis"
    "TN:Tennessee:Knoxville"
    "TN:Tennessee:Chattanooga"
    # Texas
    "TX:Texas: Houston"
    "TX:Texas: Dallas"
    "TX:Texas:Austin"
    "TX: Texas:San Antonio"
    "TX:Texas:Fort Worth"
    "TX:Texas:El Paso"
    "TX:Texas:Arlington"
    "TX:Texas: Plano"
    "TX:Texas:Corpus Christi"
    # Utah
    "UT:Utah:Salt Lake City"
    "UT:Utah:Provo"
    "UT:Utah:Ogden"
    "UT: Utah:Park City"
    # Vermont
    "VT:Vermont:Burlington"
    "VT:Vermont:Montpelier"
    "VT:Vermont:Rutland"
    # Virginia
    "VA:Virginia: Virginia Beach"
    "VA:Virginia:Richmond"
    "VA: Virginia:Norfolk"
    "VA:Virginia: Arlington"
    "VA:Virginia: Alexandria"
    "VA:Virginia: Roanoke"
    # Washington
    "WA:Washington:Seattle"
    "WA:Washington:Tacoma"
    "WA:Washington: Spokane"
    "WA:Washington:Bellevue"
    "WA:Washington: Olympia"
    "WA: Washington:Redmond"
    # West Virginia
    "WV:West Virginia: Charleston"
    "WV:West Virginia:Huntington"
    "WV: West Virginia:Morgantown"
    # Wisconsin
    "WI:Wisconsin:Milwaukee"
    "WI:Wisconsin:Madison"
    "WI:Wisconsin:Green Bay"
    "WI:Wisconsin:Kenosha"
    # Wyoming
    "WY:Wyoming:Cheyenne"
    "WY:Wyoming:Casper"
    "WY: Wyoming:Laramie"
    "WY:Wyoming:Jackson"
)

# Parodied Company Names - MEGA EDITION
declare -a COMPANIES=(
    # Big Tech
    "Foogle: Search Division:search.foogle. fake"
    "Foogle:Cloud Platform:cloud.foogle.fake"
    "Foogle: Ads Department:ads.foogle.fake"
    "Foogle:Maps Unit:maps.foogle.fake"
    "Microhard:Windows Department:windows.microhard.fake"
    "Microhard:Azure Cloud:azure.microhard.fake"
    "Microhard:Office Division:office.microhard.fake"
    "Microhard:Xbox Gaming:xbox.microhard.fake"
    "Microhard:LinkedIn Unit:jobs.microhard.fake"
    "Appel:iPhone Division:iphone.appel.fake"
    "Appel: Mac Department:mac.appel. fake"
    "Appel:iTunes Music:music.appel.fake"
    "Appel:iCloud Services:cloud.appel.fake"
    "Anazon:Prime Shipping:prime.anazon.fake"
    "Anazon:Web Services:aws.anazon.fake"
    "Anazon:Alexa Division:alexa.anazon.fake"
    "Anazon: Whole Foods:grocery.anazon.fake"
    "Meda:Social Networks:social.meda.fake"
    "Meda:Reality Labs:vr.meda.fake"
    "Meda:WhatsOops Division:chat.meda.fake"
    "Meda:Instagrain Photos:photos.meda.fake"
    
    # Social Media
    "Fecebook:Social Division:connect.fecebook.fake"
    "Fecebook: Marketplace:shop.fecebook.fake"
    "Twatter:Bird Watching:tweets.twatter.fake"
    "Twatter:Spaces Audio:spaces.twatter.fake"
    "Tiktak:Short Videos:dance.tiktak.fake"
    "Tiktak:Creator Fund:creators.tiktak.fake"
    "Snapchap:Disappearing Pics:snaps.snapchap.fake"
    "Snapchap: AR Lenses:ar.snapchap.fake"
    "Readit:Forum Division:forums.readit.fake"
    "Readit:Awards Department:gold.readit.fake"
    "Pinterust:Pinboard Services:pins.pinterust.fake"
    "Tumblar:Blogging Platform:blogs.tumblar.fake"
    "Linkdin:Professional Stalking:network.linkdin.fake"
    
    # Streaming & Entertainment
    "Netflex:Streaming Services:watch.netflex.fake"
    "Netflex:Original Content:originals.netflex.fake"
    "Spoofy:Music Streaming:listen.spoofy.fake"
    "Spoofy: Podcast Division:podcasts.spoofy. fake"
    "Twitchy:Gaming Streams:stream.twitchy.fake"
    "Twitchy: Emote Department:emotes.twitchy. fake"
    "Disword:Chat Services:voice.disword.fake"
    "Disword: Nitro Division:nitro.disword.fake"
    "Yootoob:Video Platform:watch.yootoob.fake"
    "Yootoob:Premium Services:premium.yootoob.fake"
    "Yootoob:Music Division:music.yootoob.fake"
    "Hulo:Streaming Plus:stream.hulo.fake"
    "Dizney Plus:Family Streaming:magic.dizneyplus.fake"
    "HBOMinimum:Prestige TV:prestige.hbominimum.fake"
    "Peacook:NBC Streaming:bird.peacook.fake"
    "Pandorah:Radio Services:radio.pandorah.fake"
    "Tidel:HiFi Music:hifi.tidel.fake"
    "Deeznuts:Music Platform:tunes.deeznuts.fake"
    "Crumbleroll:Anime Streaming:anime.crumbleroll.fake"
    "Funkymation:Anime Dubs: dubs.funkymation.fake"
    
    # Payments & Finance
    "Pawpal:Money Transfer:pay.pawpal.fake"
    "Pawpal:Business Payments:business.pawpal.fake"
    "Striped:Payment Processing:payments.striped.fake"
    "Squish:Point of Sale:pos.squish.fake"
    "Venmo-ish:Peer Payments:transfer.venmoish.fake"
    "Cashflap:Money App:money.cashflap.fake"
    "Coinbased:Crypto Exchange:crypto.coinbased.fake"
    "Robinghood:Stock Trading:trades.robinghood.fake"
    "Mintee:Budget Tracking:budget.mintee.fake"
    "Kredot Karma:Credit Scores:score.kredotkarma.fake"
    "Wisely:International Transfer:fx.wisely.fake"
    "Affirmed:Buy Now Pay Later: bnpl.affirmed.fake"
    "Klarny:Payment Plans:plans.klarny.fake"
    "Chimed:Banking Services:bank.chimed.fake"
    
    # Rideshare & Delivery
    "Ubah:Ride Sharing:rides.ubah.fake"
    "Ubah:Eats Delivery:food.ubah.fake"
    "Ubah:Freight Division:freight.ubah.fake"
    "Lyffed:Also Rides:cars.lyffed.fake"
    "Doorcrash:Food Delivery:deliver.doorcrash.fake"
    "Grabhub:Restaurant Delivery:grub.grabhub.fake"
    "Instacarp:Grocery Delivery:grocery.instacarp.fake"
    "Postmatos:Anything Delivery:stuff.postmatos.fake"
    "Birb:Electric Scooters:scoot.birb.fake"
    "Limey:Also Scooters:lime.limey.fake"
    
    # Travel & Hospitality
    "Airbnob:Home Rentals:stay.airbnob.fake"
    "Airbnob: Experiences:tours.airbnob.fake"
    "Bookin. con:Hotel Booking:hotels.bookincon.fake"
    "Expensedia:Travel Booking:travel.expensedia. fake"
    "Travelociraptor:Flight Deals:flights.travelociraptor.fake"
    "Kiyak:Travel Search:search.kiyak.fake"
    "TripAdvised:Travel Reviews:reviews.tripadvised.fake"
    "Vrno: Vacation Rentals:vacation.vrno.fake"
    "Hotelz. com:Last Minute: tonight.hotelzcom.fake"
    "Pricelessline:Name Your Price:bid.pricelessline.fake"
    
    # Cloud & Enterprise
    "Slaesforce:CRM Chaos:crm.slaesforce.fake"
    "Slaesforce:Marketing Cloud:marketing.slaesforce. fake"
    "Oraclol:Database Mayhem:db.oraclol.fake"
    "Oraclol:Cloud Services:cloud.oraclol.fake"
    "SAPee:Enterprise Software:erp.sapee.fake"
    "IBeeM:Legacy Systems:mainframe.ibeem.fake"
    "IBeeM:Watson AI:ai.ibeem.fake"
    "VMwhere: Virtualization:vms.vmwhere.fake"
    "Snowflunk:Data Warehouse:data.snowflunk.fake"
    "Databricks-ish:Data Platform:spark.databricksish.fake"
    "Mondaycom:Project Management:projects.mondaycom.fake"
    "Atlassican:Jira Everything:tickets.atlassican.fake"
    "Confluenze:Docs Platform:docs.confluenze.fake"
    "Sleck:Workplace Chat:work.sleck.fake"
    "Sleck:Huddles Feature:huddle.sleck.fake"
    "Zuum:Video Meetings:meet.zuum.fake"
    "Zuum:Webinar Services:webinar.zuum.fake"
    "Webecks:Enterprise Meetings:conference.webecks.fake"
    "Asanya:Task Management:tasks.asanya.fake"
    "Trellis:Kanban Boards:boards.trellis.fake"
    "Notional:Workspace Tool:notes.notional.fake"
    "Airable:Spreadsheet DB:tables.airable.fake"
    "Figmo:Design Platform:design.figmo.fake"
    "Canvar:Easy Design:create.canvar.fake"
    "Miroh:Whiteboard: collab.miroh.fake"
    
    # Developer Tools
    "Gidhub:Code Hosting:repos.gidhub.fake"
    "Gidhub:Actions CI/CD:actions.gidhub. fake"
    "Gidhub:Copiloot AI:ai.gidhub.fake"
    "Gitlob:DevOps Platform:devops.gitlob. fake"
    "Bitbucket-ish:Code Repos:git.bitbucketish.fake"
    "Dockah:Container Platform:containers.dockah.fake"
    "Kubernasty:Orchestration:k8s.kubernasty. fake"
    "Terrahform:Infrastructure: iac.terrahform.fake"
    "Ansibull:Automation:config.ansibull.fake"
    "Jenkies:CI Server:builds.jenkies.fake"
    "CircleSigh:CI Platform:ci.circlesigh.fake"
    "Travesty CI:Build Service:test.travestyci.fake"
    "Verlcel:Frontend Cloud:deploy.verlcel.fake"
    "Netliful:JAMstack Host:jam.netliful.fake"
    "Herokoo:App Platform:apps.herokoo.fake"
    "Digitall Ocean:Cloud VPS:droplets.digitallcean.fake"
    "Linerd:Linux VPS:servers.linerd.fake"
    "Vultoor:Cloud Compute:compute.vultoor.fake"
    "Cloudyflare:CDN Services:cdn.cloudyflare. fake"
    "Cloudyflare:Workers Edge:edge.cloudyflare.fake"
    "Akamoo:Edge Network:edge.akamoo.fake"
    "Fastlee:Edge Cloud:fast.fastlee.fake"
    "Auth-0h:Identity Services:auth.auth0h.fake"
    "Oktaish:SSO Provider:sso.oktaish.fake"
    "Elastish:Search Engine:search.elastish.fake"
    "Mongbongo:NoSQL Database:nosql.mongbongo.fake"
    "Reddish Labs:Cache DB:cache.reddishlabs.fake"
    "Cockroachish DB: Distributed SQL:sql.cockroachishdb.fake"
    "Planetskale:MySQL Cloud:mysql.planetskale.fake"
    "Supahbase:Firebase Alt:backend.supahbase.fake"
    "Firebased:Mobile Backend:mobile.firebased.fake"
    "Postgrizzly: Postgres Cloud:postgres.postgrizzly.fake"
    "Grafanana:Monitoring:metrics.grafanana.fake"
    "Datadawg: Observability:observe.datadawg.fake"
    "New Relish:APM Platform:apm.newrelish.fake"
    "Splonk:Log Analysis:logs.splonk.fake"
    "PagerDoodie:Incident Mgmt:oncall.pagerdoodie.fake"
    "Sentrified:Error Tracking:errors.sentrified.fake"
    
    # Hardware & Chips
    "Intol:Chip Making:cpu.intol.fake"
    "Intol:Data Center:xeon.intol.fake"
    "Nvidya:Graphics Cards:gpu.nvidya.fake"
    "Nvidya:AI Division:ai.nvidya.fake"
    "Nvidya:Gaming GeForce:gaming.nvidya.fake"
    "AMDuh:Also CPUs:ryzen.amduh.fake"
    "AMDuh: Radeon Graphics:radeon.amduh.fake"
    "Qualcommie:Mobile Chips:snapdragon.qualcommie.fake"
    "Armothy:Chip Architecture:cores.armothy.fake"
    "Cysco:Network Stuff:routers.cysco.fake"
    "Cysco: WebEx Division:meetings.cysco.fake"
    "Junipurr:Also Networks:switches.junipurr.fake"
    "Arista-crat:Cloud Network:spine.aristocrat.fake"
    "HPeee:Enterprise Servers:proliant.hpeee.fake"
    "Doll: Servers and PCs:poweredge.doll.fake"
    "Lenovoid:ThinkPads:thinkpad.lenovoid.fake"
    "ASUStoo:Motherboards: rog.asustoo.fake"
    "Gigabyted:PC Parts:aorus.gigabyted.fake"
    "Corscare:RGB Everything:rgb.corscare.fake"
    "Logiteck: Peripherals:mice.logiteck.fake"
    "Razorz:Gaming Gear:chroma.razorz.fake"
    "Steelseries-ish:Also Gaming:headsets.steelseriesish.fake"
    "Westernish Digital:Hard Drives:hdd.westernishdigital.fake"
    "Seagull Tech:Storage:barracuda.seagulltech.fake"
    "Samsong:Memory Division:ssd.samsong.fake"
    "Samsong: Galaxy Phones:galaxy.samsong.fake"
    "Sonny:PlayStation:playstation.sonny.fake"
    "Sonny:Electronics:bravia.sonny.fake"
    "Nintendoh:Gaming Consoles:switch.nintendoh.fake"
    "Xboxed:Gaming Division:series.xboxed.fake"
    
    # E-commerce & Retail
    "Shopifry:E-Commerce: store.shopifry.fake"
    "Shopifry:POS Systems:pos.shopifry.fake"
    "WooCommurce:WordPress Shop:woo.woocommurce.fake"
    "BigCommurce:Enterprise Shop:enterprise.bigcommurce.fake"
    "Etshy:Handmade Goods:crafts.etshy.fake"
    "eBey:Online Auctions:auctions.ebey.fake"
    "Wayfear:Furniture Online:furniture.wayfear.fake"
    "Chewie:Pet Supplies:pets.chewie.fake"
    "Targetted:Retail Store:bullseye.targetted.fake"
    "Walmurt:Big Box Retail:savings.walmurt.fake"
    "Costbro:Wholesale Club:bulk.costbro.fake"
    "Best Bye:Electronics Retail:geeksquad.bestbye.fake"
    "Home Despot:Home Improvement:tools.homedespot.fake"
    "Lowse:Also Home Stuff:projects.lowse.fake"
    "Macyz:Department Store:fashion.macyz.fake"
    "Nordstorm:Fancy Retail:designer.nordstorm.fake"
    "Sephorable:Beauty Products:makeup.sephorable.fake"
    "Ultamate:Beauty Retail:beauty.ultamate.fake"
    
    # Food & Beverage
    "Starblocks:Coffee Chain:coffee.starblocks.fake"
    "Starblocks:Mobile Orders:rewards.starblocks.fake"
    "Domihoes:Pizza Delivery:pizza.domihoes.fake"
    "Pizza Hoot:Also Pizza:hoot.pizzahoot.fake"
    "Chiptole:Burrito Assembly:burrito.chiptole. fake"
    "McRonalds:Fast Food:bigmac.mcronalds.fake"
    "Wendyz:Square Burgers:frosty.wendyz.fake"
    "Burger Kang:Flame Grilled:whopper.burgerkang.fake"
    "Taco Smell:Mexican Fast Food:tacos.tacosmell.fake"
    "Chickfila-ish:Chicken Sandwiches:pleasure.chickfilaish.fake"
    "Subweh:Sandwich Artist:footlong.subweh.fake"
    "Dunked Donuts:Coffee and Donuts: iced.dunkeddonuts.fake"
    "Pantera Bread:Bakery Cafe:soup.panterabread.fake"
    "Shake Shark:Burgers Premium:shack.shakeshark.fake"
    "Five Goys:Burgers Fries:peanuts.fivegoys.fake"
    "Innout Burger:West Coast Only: doubleouble.innoutburger.fake"
    "Panda Empress:Orange Chicken:wok.pandaempress.fake"
    "Olive Gardener:Italian Chain:breadsticks.olivegardener.fake"
    "Red Lobstar:Seafood Chain:biscuits.redlobstar.fake"
    
    # Gaming
    "Steamie:Game Store:store.steamie.fake"
    "Steamie:Workshop Mods:workshop.steamie.fake"
    "Epic Gamez:Also Games:fortnite.epicgamez.fake"
    "Epic Gamez:Unreal Engine:unreal.epicgamez.fake"
    "Roblecks:Kid Games:robux.roblecks.fake"
    "Minecrap:Block Game:creeper.minecrap.fake"
    "Fortniter:Battle Royale:vbucks.fortniter.fake"
    "Activizzard:Big Games:cod.activizzard.fake"
    "Electronic Farts:Sports Games:fifa.electronicfarts.fake"
    "Ubisaft:Assassin Games:uplay.ubisaft.fake"
    "Take-Twoo:GTA Maker:rockstar.taketwoo.fake"
    "Bethesduh:Buggy RPGs:skyrim.bethesduh.fake"
    "CD Projunk Red:Cyberpunk Dev:witcher. cdprojunkred.fake"
    "Riat Games:League Maker:lol.riatgames.fake"
    "Bungo: Destiny Dev:guardian.bungo.fake"
    "Resporn:Apex Legends:apex.resporn. fake"
    "Valor-ant:Tactical Shooter:agents.valorant.fake"
    
    # AI & ML
    "OpenBrain:ChatGPT Maker:gpt.openbrain.fake"
    "OpenBrain: DALL-E Images:dalle.openbrain.fake"
    "OpenBrain:Whisper Audio:whisper.openbrain. fake"
    "Antropik:Claude AI:claude.antropik.fake"
    "Antropik:Safety Research:safety.antropik.fake"
    "Deepmined:AlphaGo Maker:alpha.deepmined.fake"
    "Stablediffused:Image AI:stable.stablediffused.fake"
    "Midjurney:AI Art:imagine.midjurney.fake"
    "Huggingfaze:Model Hub:models.huggingfaze.fake"
    "Coherent AI:Enterprise LLM:enterprise.coherentai.fake"
    "AI21 Labz:Language AI:jurassic.ai21labz.fake"
    "Inflexion:Pi Assistant:personal.inflexion.fake"
    "Replicat:ML Platform:predict.replicat.fake"
    "Weightz and Biases:ML Ops:experiments.weightzbiases.fake"
    "Scaley AI:GPU Cloud:train.scaleyai.fake"
    "Runpawed:ML Compute:inference.runpawed.fake"
    
    # Security
    "Crowdstriked:Endpoint Security:falcon.crowdstriked.fake"
    "Palo Altro:Firewalls:firewall.paloaltro.fake"
    "Fortinyet:Network Security:fortigate.fortinyet.fake"
    "Zscalered:Zero Trust: ztna.zscalered. fake"
    "SentryOne:AI Security:singularity.sentryone.fake"
    "Nortin:Antivirus:lifelock.nortin.fake"
    "McAfraid:Also Antivirus:total.mcafraid.fake"
    "Bitdefendent:Security Suite:gravity.bitdefendent.fake"
    "Kasperskied:Russian AV:endpoint.kasperskied.fake"
    "Malwarebytes-ish:Malware Removal:scan.malwarebytesish.fake"
    "LastPassed:Password Manager:vault.lastpassed.fake"
    "1Passwurd:Better Passwords:secrets.1passwurd.fake"
    "Dashlain:Password Vault:autofill.dashlain.fake"
    "Bitwardan:Open Passwords:bitwarden.bitwardan.fake"
    "Keepassed:Local Passwords:keepass.keepassed.fake"
    "Nordish VPN:Virtual Network:servers.nordishvpn.fake"
    "Expressish VPN:Fast VPN:fast.expressishvpn.fake"
    "Surfshonk:Budget VPN:surf.surfshonk.fake"
    "Protonish:Swiss Privacy:mail.protonish.fake"
    "Protonish:Secure VPN:vpn.protonish.fake"
    
    # Misc Tech
    "Zilloh:Real Estate:homes.zilloh.fake"
    "Redfan:Home Buying:listings.redfan.fake"
    "Realtor-ish:Property Search:mls.realtorish.fake"
    "Yelb:Business Reviews:reviews.yelb.fake"
    "Glassdoor-ish:Company Reviews:salaries.glassdoorish.fake"
    "Indead:Job Search:jobs.indead.fake"
    "Ziprecruiter-ish:Hiring Platform:hire.ziprecruiterish.fake"
    "Carvanya:Online Cars:vending.carvanya.fake"
    "Vruum:Car Buying:cars.vruum.fake"
    "Turbotacks:Tax Software:refund.turbotacks.fake"
    "H and R Blech:Tax Filing:taxes.hrblech.fake"
    "DocuSine:E-Signatures:sign.docusine.fake"
    "HelloSine:Also Signatures:esign.hellosine.fake"
    "Mailchump:Email Marketing:campaigns.mailchump.fake"
    "Constantish Contact:Email Lists:newsletters.constantishcontact.fake"
    "Sendgriddle:Email API:smtp.sendgriddle.fake"
    "Twilyo:Communications API:sms.twilyo.fake"
    "Vonague:Business Phone:voip.vonague.fake"
    "RingCenter:Cloud Phone:ucaas.ringcenter.fake"
    "Calendlee:Scheduling:meetings.calendlee.fake"
    "Doodley:Meeting Polls:polls.doodley.fake"
    "Surveymonkee:Online Surveys:surveys.surveymonkee.fake"
    "Typefurm:Beautiful Forms:forms.typefurm. fake"
    "Grammurly:Writing Help:grammar.grammurly. fake"
    "Duolingoo:Language Learn:owl.duolingoo.fake"
    "Courserra:Online Courses:learn.courserra.fake"
    "Udamy:Video Courses:courses.udamy.fake"
    "Skillshare-ish:Creative Classes:create.skillshareish.fake"
    "Khanacadamy:Free Learning:education.khanacadamy.fake"
    "Mediumish:Blog Platform:stories.mediumish.fake"
    "Substeck:Newsletters:subscribe.substeck.fake"
    "Ghosty:Publishing:publish.ghosty.fake"
    "WordPrez:Website CMS:blog.wordprez.fake"
    "Squarish Space:Website Builder:sites.squarishspace.fake"
    "Wixed:Drag Drop Sites:websites.wixed.fake"
    "Webflew:Pro Websites:design.webflew.fake"
    "GoDaddio:Domain Registrar:domains.godaddio.fake"
    "Namecheep: Cheap Domains:register.namecheep.fake"
    "Hoostinger:Web Hosting:hosting.hoostinger.fake"
    "Bluhost:WordPress Host:wordpress.bluhost.fake"
    "Sitegrounded:Managed Host:managed.sitegrounded.fake"
)

# Pick random state/city
RANDOM_LOCATION=${STATES[$RANDOM % ${#STATES[@]}]}
IFS=': ' read -r C ST L <<< "$RANDOM_LOCATION"

# Pick random company
RANDOM_COMPANY=${COMPANIES[$RANDOM % ${#COMPANIES[@]}]}
IFS=':' read -r O OU CN <<< "$RANDOM_COMPANY"

# Certificate validity in days (100 years)
DAYS=36500

# Output filename prefix (use company name, sanitized)
PREFIX=$(echo "$O" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -cd '[:alnum:]_')

echo "=========================================="
echo "🔐 Generating SSL Certificate"
echo "=========================================="
echo "Country:       US"
echo "State:         $ST"
echo "City:         $L"
echo "Organization: $O"
echo "Unit:         $OU"
echo "Common Name:   $CN"
echo "Valid for:    $DAYS days"
echo "=========================================="
echo ""
echo "📊 Stats:  ${#STATES[@]} locations, ${#COMPANIES[@]} companies"
echo "=========================================="

# Generate the certificate
openssl req -x509 -newkey rsa: 4096 \
    -keyout "${PREFIX}_key.pem" \
    -out "${PREFIX}_cert.pem" \
    -sha256 \
    -days "$DAYS" \
    -nodes \
    -subj "/C=US/ST=$ST/L=$L/O=$O/OU=$OU/CN=$CN"

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ Certificate generated successfully!"
    echo "   Key:   ${PREFIX}_key.pem"
    echo "   Cert: ${PREFIX}_cert.pem"
    echo ""
    echo "🔍 Verify with:  openssl x509 -in ${PREFIX}_cert.pem -text -noout"
else
    echo "❌ Failed to generate certificate"
    exit 1
fi